truncate table dimPais
truncate table dimIdade
truncate table dimSexo
truncate table dimNivelAutismo
truncate table dimNivelComunicacao
truncate table dimFuncoesCognitivas
truncate table dimStatusComunicacao
truncate table dimControleEmocional
truncate table dimInteracaoSocial
truncate table dimComportamentoEsteriotipado
truncate table dimComportamento
truncate table dimFlexibilidadeInteresses
truncate table dimAutonomia
truncate table dimFrequenciaTv
truncate table dimFrequenciaVideoGames
truncate table dimJogaComAmigos
truncate table dimRedesSociais
truncate table fatIndividuos