import pandas as pd

gapminder = pd.read_excel('scripts\\base\\AUTISM-Brain sciences-Panerai et al-raw data.xlsx')

print(gapminder.info())
print(gapminder['genere M/F'].drop_duplicates().tolist())
print('-----------------------------------------------------------')
print(gapminder['diagnosi (inserire anche il livello di supporto e la compromissione intellettiva e del linguaggio)'].drop_duplicates().tolist())
print('-----------------------------------------------------------')
print(gapminder['istruzione padre/madre'].drop_duplicates().tolist())
print('-----------------------------------------------------------')
print(gapminder['Lavoro padre / madre'].drop_duplicates().tolist())
print('-----------------------------------------------------------')
print(gapminder['età cronologica in anni e mesi'].drop_duplicates().tolist())
print('-----------------------------------------------------------')
print(gapminder['età cronologica in mesi'].drop_duplicates().tolist())
print('-----------------------------------------------------------')
print(gapminder['età di sviluppo '].drop_duplicates().tolist())
print('-----------------------------------------------------------')
print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().dropna().tolist())
print('-----------------------------------------------------------')
print(gapminder['QI'].drop_duplicates().dropna().tolist())
print('-----------------------------------------------------------')
print(gapminder['test usato per il QI'].drop_duplicates().dropna().sort_values().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())
# print(gapminder['test usato per l\'età di sviluppo (PEP-3 ; Brunet Lézine; griffith; altri)'].drop_duplicates().tolist())